### ISSUE TITLE
ShaderForm, Camera Keyframes are not set correctly

### ISSUE THREAD

**Issue by Georggue** [danielscherzer/Framework#4]
Erwartetes Verhalten: Camera Uniforms werden in Keyframes übertragen.
Tatsächliches Verhalten: PosX wird übernommen, Rest ist auf 0.
Lösung: Kamera vor Forschleife zwischenspeichern, dann behält er die Werte, anscheinend wird die Kamera während der For-Schleife überschrieben.

Mein funktionierender Code:
 public void AddKeyFrames(float time, IUniforms uniforms)
  {
                OpenTK.Vector3 Pos = camera.Position;
                OpenTK.Vector3 Rot = camera.Rotation;
            

                for (int i = 0; i < 3; ++i)
                {
                    uniforms.Add(posUniformNames[i]);
                    var kfsPos = uniforms.GetKeyFrames(posUniformNames[i]);
                    kfsPos.AddUpdate(time, Pos[i]);

                    uniforms.Add(rotUniformNames[i]);
                    var kfsRot = uniforms.GetKeyFrames(rotUniformNames[i]);
                    kfsRot.AddUpdate(time, Rot[i]);
                }
}

**Comment by danielscherzer** [comment]
Danke für den Hinweis! Event loop back.  Muss mal nen mediator einbauen.
