### ISSUE TITLE
ShaderForm Feature Request "All Camera Uniforms Copy/Paste Button"

### ISSUE THREAD

**Issue by Michael-Zp** [danielscherzer/Framework#7]
### Description
Setting all camera uniforms one by one is tedious.
New tab/button, which allows the user to copy or paste all camera uniforms at once. 
Format:
Time \t XPos \t XRot \t YPos... (or similar)

**Comment by danielscherzer** [comment]
menu uniforms contains requested buttons order of export is
Time \t XPos \t YPos \t ZPos \t XRot ... \n
